### ISSUE TITLE
32-bit AMDVLK compilation fails in gpurt

### ISSUE THREAD

**Issue by v-fox** [GPUOpen-Drivers/gpurt#5]
After spending days working around DXC's cmake script bugs to satisfy gpurt's dependency in amdvlk, I managed to successfully make a 64-bit amdvlk package but not 32-bit due to persistent `too many elements in vector initialization` and `if statement conditional expressions must evaluate to a scalar` errors: [amdvlk_gpurt.log](https://github.com/GPUOpen-Drivers/gpurt/files/9582854/amdvlk_gpurt.log)

**Comment by Flakebi** [comment]
Building a 32-bit package is working fine for me with dxc 1.7.2207 (and seems to work for the official Ubuntu packages as well). Which dxc are you using?

**Comment by v-fox** [comment]
> Building a 32-bit package is working fine for me with dxc 1.7.2207 (and seems to work for the official Ubuntu packages as well). Which dxc are you using?

3 days old commit: https://github.com/microsoft/DirectXShaderCompiler/commit/79856c4a7
Their tag on the main branch seems wrong, so packaging script gets '1.4.0.2274+1249~git20220913.79856c4a7' version but it's '1.7.2207.0' in utils/version.

**Comment by qiaojbao** [comment]
Currently, we use 1.6.2 dxc version, we will verify more versions later.
You could use this version first.

git clone --depth=1 -b release-1.6.2112 https://github.com/microsoft/DirectXShaderCompiler.git
cd DirectXShaderCompiler
git submodule init
git submodule update
cmake -H. -Bbuilds -GNinja -DCMAKE_BUILD_TYPE=Release -C ./cmake/caches/PredefinedParams.cmake
cmake --build builds

We did not meet any CMake bugs for dxc build.

Also, you could install vulkan-sdk to get dxc tools if you use ubuntu system.

**Comment by LAKostis** [comment]
Still reproducible with v2022.Q3.5 and dxc from release-1.6.2112 branch GIT 6f204c7. Build log attached
[amdvlk_gpurt_alt-32.log](https://github.com/GPUOpen-Drivers/gpurt/files/9793083/amdvlk_gpurt_alt-32.log)

**Comment by LAKostis** [comment]
Still reproducible with v2022.Q4.1 and dxc from release-1.7.2207 GIT e3f322389dadc5d5370bc8e17d3494a7909b6238. Build log attached
[build.log.i586.txt](https://github.com/GPUOpen-Drivers/gpurt/files/9843928/build.log.i586.txt)

**Comment by LAKostis** [comment]
Okay, the build failure was caused by LTO enabled in dxc + missing ` -DCMAKE_BUILD_TYPE=Release` flag. So 2022.Q4.2 + release-1.6.2112 works now.

**Comment by Flakebi** [comment]
After encountering the same (?) issue in NixOS, it looks like

1. the issue surfaces when building gpurt with a 32-bit directx-shader-compiler that was built with **gcc 12**
2. the issue goes away after updating dxc to **1.7.2212.1** and amdvlk to **2023.Q1.3** (https://github.com/NixOS/nixpkgs/pull/222072).

Can you try if compilation works for you with these dxc and amdvlk versions?

**Comment by v-fox** [comment]
> Can you try if compilation works for you with these dxc and amdvlk versions?

No changes for me.
My working 64-bit build of dxc is built with clang-15 while 32-bit build is done by gcc-12 because otherwise it fails with `lib/DxcSupport/WinFunctions.cpp:134:15: error: definition of builtin function '_BitScanForward'`. Maybe that has something to do with it. So I just build 32-bit amdvlk with `-DVKI_RAY_TRACING=OFF ` for now.

**Comment by LAKostis** [comment]
> After encountering the same (?) issue in NixOS, it looks like
> 
>     1. the issue surfaces when building gpurt with a 32-bit directx-shader-compiler that was built with **gcc 12**
In my case it builds fine with gcc-12 but with dxc 1.6.2112.

> 
>     2. the issue goes away after updating dxc to **1.7.2212.1** and amdvlk to **2023.Q1.3** ([directx-shader-compiler: remove pinned stdenv workaround NixOS/nixpkgs#222072](https://github.com/NixOS/nixpkgs/pull/222072)).
> 
> 
> Can you try if compilation works for you with these dxc and amdvlk versions?
How you compile 1.7.2212.1 if it fails on linux due [conflicting types](https://github.com/microsoft/DirectXShaderCompiler/issues/5079) in directx-headers?

**Comment by Flakebi** [comment]
> No changes for me.

Ok, thanks for trying!

> How you compile 1.7.2212.1 if it fails on linux due conflicting types in directx-headers?

You only need the dxc binary, we don’t use directx-headers anywhere.
The nix package build for dxc looks like this: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/graphics/directx-shader-compiler/default.nix

**Comment by LAKostis** [comment]
> > No changes for me.
> 
> Ok, thanks for trying!
> 
> > How you compile 1.7.2212.1 if it fails on linux due conflicting types in directx-headers?
> 
> You only need the dxc binary, we don’t use directx-headers anywhere. The nix package build for dxc looks like this: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/graphics/directx-shader-compiler/default.nix

I see that you checkout submodules too (which includes DirectX-Headers), so in fact headers are in use.  But I'm puzzled why compilation doesn't fail in your case. Nevertheless, this is out of scope, maybe it's my local misconfiguration.

**Comment by LAKostis** [comment]
For those who interested about directx-headers:
`$ git submodule update
Cloning into '/home/lakostis/local/src/git/work/DirectXShaderCompiler/external/DirectX-Headers'...
Cloning into '/home/lakostis/local/src/git/work/DirectXShaderCompiler/external/SPIRV-Headers'...
Cloning into '/home/lakostis/local/src/git/work/DirectXShaderCompiler/external/SPIRV-Tools'...
Cloning into '/home/lakostis/local/src/git/work/DirectXShaderCompiler/external/effcee'...
Cloning into '/home/lakostis/local/src/git/work/DirectXShaderCompiler/external/re2'...
Submodule path 'external/DirectX-Headers': checked out '980971e835876dc0cde415e8f9bc646e64667bf7'
...
`
But commit `980971e835876dc0cde415e8f9bc646e64667bf7` is not in latest version of DirectX-Headers but in version `1.600.10`.

**Comment by LAKostis** [comment]
> After encountering the same (?) issue in NixOS, it looks like
> 
>     1. the issue surfaces when building gpurt with a 32-bit directx-shader-compiler that was built with **gcc 12**
> 
>     2. the issue goes away after updating dxc to **1.7.2212.1** and amdvlk to **2023.Q1.3** ([directx-shader-compiler: remove pinned stdenv workaround NixOS/nixpkgs#222072](https://github.com/NixOS/nixpkgs/pull/222072)).
> 
> 
> Can you try if compilation works for you with these dxc and amdvlk versions?

I can confirm that everything works with dxc **1.7.2212.1** and amdvlk to **2023.Q1.3** both for [i586 and x86_64](https://packages.altlinux.org/en/tasks/317273/).

**Comment by LAKostis** [comment]
32-bit compilation fails again with recent dxc **1.8.2502** and 2025.02.1:
```
[00:05:34] Compilation failed for shader GpuRtLibrarySwDev
[00:05:34] Output log:
[00:05:34] Subprocess invocation failed. Error code -1. Additional details follow:
[00:05:34] Environment: {'RPM_PYTHON_COMPILE_INCLUDE': '/usr/lib /usr/lib', 'RPM_FIXUP_TOPDIR': '', 'RPM_PYTHON3_SELF_PROV_PATH': '', 'RPM_SOURCE_DIR': '/usr/src/RPM/SOURCES', 'RPM_PKG_CONTENTS_INDEX_BIN': '/.host/contents_index_bin', 'RPM_PYTHON_LIB_PATH': '', 'RPM_PYTHON3_VERSION': '3.12', 'G_BROKEN_FILENAMES': '1', 'HISTSIZE': '999', 'HOSTNAME': 'localhost.localdomain', 'RPM_PYTHON3_SITELIBDIR': '/usr/lib/python3/site-packages', 'RPM_PYTHON': '/usr/bin/python2.7', 'RPM_PYTHON3_COMPILE_EXCLUDE': '/usr/share/doc', 'RPM_PYTHON_COMPILE_DEEP': '20', 'RPM_PYTHON3_SITELIBDIR_NOARCH': '/usr/lib/python3/site-packages', 'RPM_PYTHON_COMPILE_SKIP_X': '1', 'RPM_PYTHON_COMPILE_EXCLUDE': '/usr/share/doc', 'RPM_LIB': 'lib', 'RPM_FIXUP_METHOD': 'binconfig pkgconfig libtool desktop gnuconfig', 'RPM_LD_PRELOAD_python': '/usr/lib/libpython2.7.so', 'PWD': '/usr/src/RPM/BUILD/xgl/i586-alt-linux/gpurt/src', 'RPM_CLEANUP_TOPDIR': '', 'SOURCE_DATE_EPOCH': '1747504382', 'LOGNAME': 'builder', 'RPM_PYTHON3_COMPILE_SKIP_X': '1', 'RPM_VERIFY_ELF_METHOD': 'default', 'RPM_FILES_TO_LD_PRELOAD_python': ' /usr/lib/python2.7/* /usr/lib/python2.7/site-packages/* /usr/lib/python2.7/site-packages/*', 'RPM_CLEANUP_SKIPLIST': '', 'RPM_ARCH': 'i586', 'HOME': '/usr/src', 'RPM_DATADIR': '/usr/share', 'RPM_PYTHON3_COMPILE_CLEAN': '1', 'RPM_FILES_TO_LD_PRELOAD_python3': ' /usr/lib/python3/site-packages/* /usr/lib/python3/site-packages/*', 'PERL_USE_UNSAFE_INC': '1', 'RPM_PERL_REQ_METHOD': 'normal', 'RPM_PYTHON_REQ_METHOD': 'slight', 'RPM_TARGET_ARCH': 'i586', 'RPM_PYTHON3': '/usr/bin/python3', 'RPM_FINDPROV_LIB_PATH': '', 'RPM_COMPRESS_TOPDIR': '/usr', 'TMPDIR': '/usr/src/tmp', 'RPM_VERIFY_ELF_TOPDIR': '', 'RPM_CHECK_CONTENTS_METHOD': 'default', 'RPM_FINDPROV_TOPDIR': '', 'RPM_PACKAGE_RELEASE': 'alt2', 'RPM_DEBUGINFO_SKIPLIST': '', 'RPM_PYTHON_COMPILE_CLEAN': '1', 'RPM_OS': 'linux', 'RPM_VERIFY_ELF_SKIPLIST': '', 'ALTWRAP_LLVM_VERSION': '20.1', 'MAKEFLAGS': '-w -O PAM_SO_SUFFIX=', 'RPM_CHECK_CONTENTS_SKIPLIST': '', 'TERM': 'dumb', 'RPM_PYTHON3_REQ_METHOD': 'slight', 'USER': 'builder', 'RPM_PYTHON3_LIBDIR': '/usr/lib/python3.12', 'RPM_PYTHON3_PATH': '/usr/lib/python3/site-packages /usr/lib/python3/site-packages', 'PAM_SO_SUFFIX': '', 'RPM_TARGET_OS': 'linux', 'SHLVL': '2', 'RPM_BUILD_DIR': '/usr/src/RPM/BUILD', 'RPM_FINDREQ_TOPDIR': '', 'RPM_FIXUP_SKIPLIST': '', 'PAM_NAME_SUFFIX': '', 'RPM_PYTHON2_PATH': '/usr/lib/python2.7/site-packages /usr/lib/python2.7/site-packages', 'RPM_PYTHON3_COMPILE_DEEP': '20', 'RPM_OPT_FLAGS': '-pipe -frecord-gcc-switches -Wall -g0 -O3  -march=i586 -mtune=generic', 'RPM_PYTHON3_REQ_HIER': 'yes', 'RPM_FINDREQ_SKIPLIST': '/usr/share/doc/*', 'RPM_PYTHON3_IMPORT_PATH': '', 'RPM_DOC_DIR': '/usr/share/doc', 'RPM_VERIFY_INFO_METHOD': 'normal', 'RPM_PACKAGE_VERSION': '2025.Q2.1', 'RPM_STRICT_INTERDEPS': 'sisyphus.384497.200.1.1', 'RPM_PYTHON3_COMPILE_INCLUDE': '/usr/lib/python3/site-packages /usr/lib/python3/site-packages', 'RPM_PYTHON_MODULE_DECLARED': '', 'RPM_PYTHON_REQ_SKIP': '', 'RPM_LIBDIR': '/usr/lib', 'RPM_LD_PRELOAD_python3': '/usr/lib/libpython3.12.so', 'RPM_PYTHON_COMPILE_METHOD': 'ALL', 'RPM_PYTHON3_REQ_SKIP': '', 'PATH': '/usr/src/bin:/usr/bin:/bin:/usr/local/bin:/usr/games', 'RPM_CHECK_CONTENTS_TOPDIR': '', 'HISTFILESIZE': '9999', 'MAIL': '/var/mail/builder', 'RPM_FINDPROV_SKIPLIST': '/usr/share/doc/*', 'RPM_FINDPACKAGE_PATH': '', 'RPM_COMPRESS_SKIPLIST': '', 'RPM_PACKAGE_NAME': 'vulkan-amdgpu', 'RPM_CLEANUP_METHOD': 'auto', 'RPM_BUILD_ROOT': '/usr/src/tmp/vulkan-amdgpu-buildroot', 'OLDPWD': '/usr/src/RPM/BUILD/xgl/i586-alt-linux', 'RPM_COMPRESS_METHOD': 'auto', 'RPM_PYTHON3_LIB_PATH': '', '_': '/usr/bin/python3.12', 'LC_CTYPE': 'C.UTF-8', 'LD_LIBRARY_PATH': ''}
[00:05:34] Command arguments: ['dxc', '-I', '/usr/src/RPM/BUILD/xgl/i586-alt-linux/gpurt/src', '-I', '/usr/src/RPM/BUILD/xgl/i586-alt-linux/icd/llpc_version/include', '-I', '/usr/src/RPM/BUILD/llpc/version/include', '-Vd', '-O3', '-spirv', '-fspv-target-env=universal1.5', '-fcgl', '-DAMD_VULKAN', '-DAMD_VULKAN_DXC', '-DAMD_VULKAN_SPV', '-fvk-use-scalar-layout', '-Wall', '-Wextra', '-Wno-ignored-attributes', '-Wno-unused-variable', '-Wno-unused-function', '-Wno-unused-parameter', '-Wno-sometimes-uninitialized', '-Wno-conversion', '-enable-16bit-types', '-T', 'lib_6_3', '-HV', '2018', '-DGPURT_BUILD_RTIP3=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_BUILD_RTIP3_1=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_DEVELOPER=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_BUILD_CONTINUATION=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_CLIENT_INTERFACE_MAJOR_VERSION=56', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DPAL_CLIENT_INTERFACE_MAJOR_VERSION=924', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DLLPC_CLIENT_INTERFACE_MAJOR_VERSION=76', '-DLITTLEENDIAN_CPU', '-DLLPC_BUILD_HAWK_POINT1=1', '-DLLPC_BUILD_HAWK_POINT2=1', '-DLLPC_BUILD_STRIX1=1', '-DLLPC_BUILD_STRIX_HALO=1', '-DLLPC_BUILD_NAVI48=1', '-DGPURT_CLIENT_API_VULKAN=1', '-DDEVELOPER=1', '-DGPURT_RTIP_LEVEL=0', '-DGPURT_RTIP_LEGACY_LEVEL=30', '-Fo', 'GpuRtLibrarySwDev.spv', '/usr/src/RPM/BUILD/gpurt/src/shaders/GpuRtLibrary.hlsl']
[00:05:34] Expected empty output: True
[00:05:34] Working directory: /usr/src/RPM/BUILD/xgl/i586-alt-linux/gpurt/src/pipelines/GpuRtLibrarySwDev
[00:05:34] Stdout:
[00:05:34] 
[00:05:34] Stderr:
[00:05:34] In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/GpuRtLibrary.hlsl:39:
[00:05:34] In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/GpuRtLibraryCont.hlsl:1273:
[00:05:34] In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/Continuations3_1.hlsl:26:
[00:05:34] In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/rtip3_ops.hlsl:76:
[00:05:34] /usr/src/RPM/BUILD/gpurt/src/shaders/rtip3_opcode_emulation.hlsl:754:87: error: cannot initialize a parameter of type 'vector<uint, 4>' with an lvalue of type 'vector<uint, 2>'
[00:05:34]     result.origin                                     = float3(asfloat(d0.w), asfloat(d1.xy));
[00:05:34]                                                                                       ^~~~~
[00:05:34] Compiling (dxc spirv=True) GpuRtLibrary.hlsl<Library> -> GpuRtLibrarySwDev_spv.h...Failure
[00:05:34] Failed to compile Vulkan shader config ShaderConfig< Path: GpuRtLibrary.hlsl, EntryPoint: None, OutputName: GpuRtLibrarySwDev, Defines: GPURT_BUILD_RTIP3=1,NOMINMAX,WIN32_LEAN_AND_MEAN,GPURT_BUILD_RTIP3_1=1,NOMINMAX,WIN32_LEAN_AND_MEAN,GPURT_DEVELOPER=1,NOMINMAX,WIN32_LEAN_AND_MEAN,NOMINMAX,WIN32_LEAN_AND_MEAN,GPURT_BUILD_CONTINUATION=1,NOMINMAX,WIN32_LEAN_AND_MEAN,GPURT_CLIENT_INTERFACE_MAJOR_VERSION=56,NOMINMAX,WIN32_LEAN_AND_MEAN,PAL_CLIENT_INTERFACE_MAJOR_VERSION=924,NOMINMAX,WIN32_LEAN_AND_MEAN,LLPC_CLIENT_INTERFACE_MAJOR_VERSION=76,LITTLEENDIAN_CPU,LLPC_BUILD_HAWK_POINT1=1,LLPC_BUILD_HAWK_POINT2=1,LLPC_BUILD_STRIX1=1,LLPC_BUILD_STRIX_HALO=1,LLPC_BUILD_NAVI48=1,GPURT_CLIENT_API_VULKAN=1,DEVELOPER=1,GPURT_RTIP_LEVEL=0,GPURT_RTIP_LEGACY_LEVEL=30, isBVH: False >
```
It still compiles with dxc **1.8.2403**.

**Comment by LAKostis** [comment]
Now it even fails with dxc 1.8.2403 (can be reproduced steadily) @qiaojbao is there any plans to update recommended dxc version?
```
Subprocess invocation failed. Error code -1. Additional details follow:
Environment: {'RPM_PYTHON_COMPILE_INCLUDE': '/usr/lib /usr/lib', 'RPM_FIXUP_TOPDIR': '', 'RPM_PYTHON3_SELF_PROV_PATH': '', 'RPM_SOURCE_DIR': '/usr/src/RPM/SOURCES', 'RPM_PKG_CONTENTS_INDEX_BIN': '/.host/contents_index_bin', 'RPM_PYTHON_LIB_PATH': '', 'RPM_PYTHON3_VERSION': '3.12', 'G_BROKEN_FILENAMES': '1', 'HISTSIZE': '999', 'HOSTNAME': 'localhost.localdomain', 'RPM_PYTHON3_SITELIBDIR': '/usr/lib/python3/site-packages', 'RPM_PYTHON': '/usr/bin/python2.7', 'RPM_PYTHON3_COMPILE_EXCLUDE': '/usr/share/doc', 'RPM_PYTHON_COMPILE_DEEP': '20', 'RPM_PYTHON3_SITELIBDIR_NOARCH': '/usr/lib/python3/site-packages', 'RPM_PYTHON_COMPILE_SKIP_X': '1', 'RPM_PYTHON_COMPILE_EXCLUDE': '/usr/share/doc', 'RPM_LIB': 'lib', 'RPM_FIXUP_METHOD': 'binconfig pkgconfig libtool desktop gnuconfig', 'RPM_LD_PRELOAD_python': '/usr/lib/libpython2.7.so', 'PWD': '/usr/src/RPM/BUILD/xgl/i586-alt-linux/gpurt/src', 'RPM_CLEANUP_TOPDIR': '', 'SOURCE_DATE_EPOCH': '1747504382', 'LOGNAME': 'builder', 'RPM_PYTHON3_COMPILE_SKIP_X': '1', 'RPM_VERIFY_ELF_METHOD': 'default', 'RPM_FILES_TO_LD_PRELOAD_python': ' /usr/lib/python2.7/* /usr/lib/python2.7/site-packages/* /usr/lib/python2.7/site-packages/*', 'RPM_CLEANUP_SKIPLIST': '', 'RPM_ARCH': 'i586', 'HOME': '/usr/src', 'RPM_DATADIR': '/usr/share', 'RPM_PYTHON3_COMPILE_CLEAN': '1', 'RPM_FILES_TO_LD_PRELOAD_python3': ' /usr/lib/python3/site-packages/* /usr/lib/python3/site-packages/*', 'PERL_USE_UNSAFE_INC': '1', 'RPM_PERL_REQ_METHOD': 'normal', 'RPM_PYTHON_REQ_METHOD': 'slight', 'RPM_TARGET_ARCH': 'i586', 'RPM_PYTHON3': '/usr/bin/python3', 'RPM_FINDPROV_LIB_PATH': '', 'RPM_COMPRESS_TOPDIR': '/usr', 'TMPDIR': '/usr/src/tmp', 'RPM_VERIFY_ELF_TOPDIR': '', 'RPM_CHECK_CONTENTS_METHOD': 'default', 'RPM_FINDPROV_TOPDIR': '', 'RPM_PACKAGE_RELEASE': 'alt2', 'RPM_DEBUGINFO_SKIPLIST': '', 'RPM_PYTHON_COMPILE_CLEAN': '1', 'RPM_OS': 'linux', 'RPM_VERIFY_ELF_SKIPLIST': '', 'ALTWRAP_LLVM_VERSION': '20.1', 'MAKEFLAGS': '-w -O PAM_SO_SUFFIX=', 'RPM_CHECK_CONTENTS_SKIPLIST': '', 'TERM': 'dumb', 'RPM_PYTHON3_REQ_METHOD': 'slight', 'USER': 'builder', 'RPM_PYTHON3_LIBDIR': '/usr/lib/python3.12', 'RPM_PYTHON3_PATH': '/usr/lib/python3/site-packages /usr/lib/python3/site-packages', 'PAM_SO_SUFFIX': '', 'RPM_TARGET_OS': 'linux', 'SHLVL': '2', 'RPM_BUILD_DIR': '/usr/src/RPM/BUILD', 'RPM_FINDREQ_TOPDIR': '', 'RPM_FIXUP_SKIPLIST': '', 'PAM_NAME_SUFFIX': '', 'RPM_PYTHON2_PATH': '/usr/lib/python2.7/site-packages /usr/lib/python2.7/site-packages', 'RPM_PYTHON3_COMPILE_DEEP': '20', 'RPM_OPT_FLAGS': '-pipe -frecord-gcc-switches -Wall -g0 -O3  -march=i586 -mtune=generic', 'RPM_PYTHON3_REQ_HIER': 'yes', 'RPM_FINDREQ_SKIPLIST': '/usr/share/doc/*', 'RPM_PYTHON3_IMPORT_PATH': '', 'RPM_DOC_DIR': '/usr/share/doc', 'RPM_VERIFY_INFO_METHOD': 'normal', 'RPM_PACKAGE_VERSION': '2025.Q2.1', 'RPM_PYTHON3_COMPILE_INCLUDE': '/usr/lib/python3/site-packages /usr/lib/python3/site-packages', 'RPM_PYTHON_MODULE_DECLARED': '', 'RPM_PYTHON_REQ_SKIP': '', 'RPM_LIBDIR': '/usr/lib', 'RPM_LD_PRELOAD_python3': '/usr/lib/libpython3.12.so', 'RPM_PYTHON_COMPILE_METHOD': 'ALL', 'RPM_PYTHON3_REQ_SKIP': '', 'PATH': '/usr/src/bin:/usr/bin:/bin:/usr/local/bin:/usr/games', 'RPM_CHECK_CONTENTS_TOPDIR': '', 'HISTFILESIZE': '9999', 'MAIL': '/var/mail/builder', 'RPM_FINDPROV_SKIPLIST': '/usr/share/doc/*', 'RPM_FINDPACKAGE_PATH': '', 'RPM_COMPRESS_SKIPLIST': '', 'RPM_PACKAGE_NAME': 'vulkan-amdgpu', 'RPM_CLEANUP_METHOD': 'auto', 'RPM_BUILD_ROOT': '/usr/src/tmp/vulkan-amdgpu-buildroot', 'OLDPWD': '/usr/src/RPM/BUILD/xgl/i586-alt-linux', 'RPM_COMPRESS_METHOD': 'auto', 'RPM_PYTHON3_LIB_PATH': '', '_': '/usr/bin/python3.12', 'LC_CTYPE': 'C.UTF-8', 'LD_LIBRARY_PATH': ''}
Command arguments: ['dxc', '-I', '/usr/src/RPM/BUILD/xgl/i586-alt-linux/gpurt/src', '-I', '/usr/src/RPM/BUILD/xgl/i586-alt-linux/icd/llpc_version/include', '-I', '/usr/src/RPM/BUILD/llpc/version/include', '-Vd', '-O3', '-spirv', '-fspv-target-env=universal1.5', '-fcgl', '-DAMD_VULKAN', '-DAMD_VULKAN_DXC', '-DAMD_VULKAN_SPV', '-fvk-use-scalar-layout', '-Wall', '-Wextra', '-Wno-ignored-attributes', '-Wno-unused-variable', '-Wno-unused-function', '-Wno-unused-parameter', '-Wno-sometimes-uninitialized', '-Wno-conversion', '-enable-16bit-types', '-T', 'lib_6_3', '-HV', '2018', '-DGPURT_BUILD_RTIP3=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_BUILD_RTIP3_1=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_DEVELOPER=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_BUILD_CONTINUATION=1', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DGPURT_CLIENT_INTERFACE_MAJOR_VERSION=56', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DPAL_CLIENT_INTERFACE_MAJOR_VERSION=924', '-DNOMINMAX', '-DWIN32_LEAN_AND_MEAN', '-DLLPC_CLIENT_INTERFACE_MAJOR_VERSION=76', '-DLITTLEENDIAN_CPU', '-DLLPC_BUILD_HAWK_POINT1=1', '-DLLPC_BUILD_HAWK_POINT2=1', '-DLLPC_BUILD_STRIX1=1', '-DLLPC_BUILD_STRIX_HALO=1', '-DLLPC_BUILD_NAVI48=1', '-DGPURT_CLIENT_API_VULKAN=1', '-DUSE_HW_INTRINSIC=1', '-DDEVELOPER=1', '-DGPURT_RTIP_LEVEL=30', '-DGPURT_RTIP_LEGACY_LEVEL=30', '-Fo', 'GpuRtLibraryDevLegacy.spv', '/usr/src/RPM/BUILD/gpurt/src/shaders/GpuRtLibrary.hlsl']
Expected empty output: True
Working directory: /usr/src/RPM/BUILD/xgl/i586-alt-linux/gpurt/src/pipelines/GpuRtLibraryDevLegacy
Stdout:

Stderr:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/GpuRtLibrary.hlsl:34:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/TraceRayCommon.hlsl:27:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/IntersectCommon.hlsl:28:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/Common.hlsli:531:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/Common.hlsl:37:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/ScratchNode.hlsli:29:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/BoxNode1_0.hlsli:173:
/usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/BoxNode1_0.hlsl:102:29: error: too few elements in vector initialization (expected 3 elements, have 2)
    node.bbox0_max = float3(asfloat(d1.w), asfloat(d2.xy));
                            ^
/usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/BoxNode1_0.hlsl:103:29: error: too few elements in vector initialization (expected 3 elements, have 2)
    node.bbox1_min = float3(asfloat(d2.zw), asfloat(d3.x));
                            ^
/usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/BoxNode1_0.hlsl:106:29: error: too few elements in vector initialization (expected 3 elements, have 2)
    node.bbox2_max = float3(asfloat(d4.w), asfloat(d5.xy));
                            ^
/usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/BoxNode1_0.hlsl:107:29: error: too few elements in vector initialization (expected 3 elements, have 2)
    node.bbox3_min = float3(asfloat(d5.zw), asfloat(d6.x));
                            ^
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/GpuRtLibrary.hlsl:34:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/TraceRayCommon.hlsl:27:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/IntersectCommon.hlsl:28:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/Common.hlsli:531:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/Common.hlsl:42:
In file included from /usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/ProceduralNode1_0.hlsli:86:
/usr/src/RPM/BUILD/gpurt/src/shaders/../shadersClean/common/gfx10/ProceduralNode1_0.hlsl:44:28: error: too few elements in vector initialization (expected 3 elements, have 2)
    node.bbox_max = float3(asfloat(d0.w), asfloat(d1.xy));
                           ^
...

error: Bad exit status from /usr/src/tmp/rpm-tmp.41911 (%build)
```

**Comment by qiaojbao** [comment]
https://github.com/microsoft/DirectXShaderCompiler/tree/staging-sm6.9
